name: artifact

on:
  push:
    branches: [release-*]

defaults:
  run:
    working-directory: ./haskell

jobs:
  artifact:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        ghc: ['9.2']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: ln -s cabal.project.${{ matrix.ghc }}.freeze cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ./haskell/dist-newstyle
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/haskell/cabal.project.freeze') }}
          restore-keys: cabal-${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal update
      - run: make install CABAL_OPTS='--install-method=copy --installdir=./out'
      - uses: actions/upload-artifact@v3
        with:
          name: wd-${{ github.ref_name }}-${{ matrix.ghc }}-${{ matrix.os }}
          path: ./haskell/out/wd*
          if-no-files-found: error
