name: haskell

on:
  - push
  - pull_request

defaults:
  run:
    working-directory: ./haskell

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0', '9.2']
        continue-on-error: [false]
        include:
          - ghc: latest
            continue-on-error: true

    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.continue-on-error }}

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: ln -s cabal.project.${{ matrix.ghc }}.freeze cabal.project.freeze
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ./haskell/dist-newstyle
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('/haskell/cabal.project.freeze') }}
          restore-keys: cabal-${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal update
      - run: make build-deps
      - run: make build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/hlint-setup@v2
      - run: make lint

  # Stop until merging https://github.com/haskell/stylish-haskell/pull/420
  # format:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: curl -sL https://raw.github.com/haskell/stylish-haskell/master/scripts/latest.sh | sh -s -- --inplace --recursive .
  #     - run: git diff --exit-code
