name: c

on:
  - push
  - pull_request

jobs:
  build-linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./linux

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build

  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./windows

    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
      - run: msbuild
